using IdentityServiceApi.Models.ServiceResultModels.Shared;

namespace IdentityServiceApi.Models.ServiceResultModels.Authentication
{
    /// <summary>
    ///     Represents the result of a login-related operation performed by the login service.
    /// </summary>
    /// <remarks>
    ///     @Author: Christian Briglio
    ///     @Created: 2024
    /// </remarks>
    public class LoginServiceResult : ServiceResult
    {
        /// <summary>
        ///     Token generated by login service after user is successfully authenticated.
        /// </summary>
        public string Token { get; set; }
    }
}
