
namespace AspNetWebService.Models.ServiceResultModels.LoginServiceResults
{
    /// <summary>
    ///     Represents the result of a login-related operation performed by the login service.
    /// </summary>
    /// <remarks>
    ///     @Author: Christian Briglio
    /// </remarks>
    public class LoginServiceResult
    {
        /// <summary>
        ///     Token generated by login service after user is successfully authenticated.
        /// </summary>
        public string Token { get; set; }

        /// <summary>
        ///     Indicates whether the role operation was successful.
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        ///     Contains errors encountered during the login operation, if any.
        /// </summary>
        public List<string> Errors { get; set; } = new List<string>();
    }
}
