
namespace AspNetWebService.Models.ServiceResultModels.LoginServiceResults
{
    /// <summary>
    ///     Represents the result of a login-related operation performed by the login service.
    /// </summary>
    /// <remarks>
    ///     @Author: Christian Briglio
    /// </remarks>
    public class LoginServiceResult : ServiceResult
    {
        /// <summary>
        ///     Token generated by login service after user is successfully authenticated.
        /// </summary>
        public string Token { get; set; }
    }
}
